### ISSUE TITLE
windows encoding error 

### ISSUE THREAD

**Issue by akadon** [DenTechs/Virtual_Desktop_Body_Tracking_Configurator#2]
Exception has occurred: UnicodeDecodeError 'utf-8' codec can't decode byte 0x81 in position 74: invalid start byte File

newest version throws an error on start 

<img width="250" alt="11111" src="https://github.com/DenTechs/Virtual_Desktop_Body_Tracking_Configurator/assets/40471927/c1da810b-666e-4c43-9cd0-ddaf71e9c846">

**Comment by akadon** [comment]
I made a pull request to fix this problem #3

**Comment by DenTechs** [comment]
I've found this error occurs if you have a non-english system language, it also occurs when reading/writing to files with some languages. There's a fix by going into windows region settings and enabling a beta feature for utf-8 encoding for worldwide languages. I'll take a look at the PR though :)
https://cdn.discordapp.com/attachments/952979951286628362/1215394451405537381/image.png?ex=65fc974a&is=65ea224a&hm=2fe4901171eaf8588b3f42ba28fb4a696ef5897b0bd93f04e15f9f7fc97625ab&

https://cdn.discordapp.com/attachments/952979951286628362/1215394451715919952/image.png?ex=65fc974a&is=65ea224a&hm=f58d95a5ea9861be1c23526c6a0ce45f634c722e6de58b0d06de4b0ed488ecdd&

https://cdn.discordapp.com/attachments/952979951286628362/1215394452252663879/image.png?ex=65fc974a&is=65ea224a&hm=b8d8729c64a588693fddfa22eccf0d0de42dec3bdf0f49aa87c4f16afdceafc5&

**Comment by DenTechs** [comment]
Hmm no, looking back seems like the reading/writing issue is from the same cause of non-standard cases, but the error is a bit different. I'll merge your fix for now and i'll see if i can't figure something out for the path.
![2024-03-01_002456](https://github.com/DenTechs/Virtual_Desktop_Body_Tracking_Configurator/assets/48604154/511b2f6f-d8e5-41e6-a039-b2170bd1cc75)

**Comment by DenTechs** [comment]
Aha, found i can manually set the encoding when reading the json files to utf-8 fixing the issue, thanks!
